function projectShutdown()
    
    thisProject = slproject.getCurrentProject;
    rootFolder  = thisProject.RootFolder;  
    cd(rootFolder);
    
    % If you modified the root folders in which to put files generated by
    % diagram updates and model builds, reset this setting in Simulink
    % Preferences.
    Simulink.fileGenControl('reset', 'keepPreviousPath', true)

    
end


